rust_log = "debug,tower_http=error,hyper_util=error,rustify=off"

[api]
url = "0.0.0.0"
port = 3000

[loki]
url = "http://localhost:3100"
service_name = "kraken"

[database]
url = "localhost"
port = 5432
username = "postgres"
password = "password"
