services:
  postgres:
    image: "postgres:alpine"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data:rw
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=datafed
      - PGDATA=/data

  grafana:
    image: "grafana/grafana"
    depends_on:
      - prometheus
      - loki
      - tempo
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - 8080:8080

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  loki:
    image: "grafana/loki"
    ports:
      - 3100:3100

  # tempo:
  #   image: "grafana/tempo"
  #   command: ["-config.file=/etc/tempo.yml"]
  #   volumes:
  #     - ./tempo.yml:/etc/tempo.yml
  #     - tempo-data:/var/tempo
  #   ports:
  #     - 4318:4318
  #     - 3200:3200

volumes:
  pgdata:
  grafana-data:
  # tempo-data:
