stages:
  - build

include:
  - local: .gitlab/common.yml

build-foxx:
  extends: .docker_build_script
  stage: build
  variables:
    IMAGE_TAG: "datafed/foxx"
    GIT_STRATEGY: clone
    DOCKER_FILE_PATH: "docker/Dockerfile.foxx"
  tags:
    - docker
  rules:
    - changes:
        - docker/**/*
        - scripts/**/*
        - web/**/*
        - common/proto/**/*
        - .gitlab-ci.yml
      when: on_success

placeholder:
  extends: .placeholder
