stages:
  - build

include:
  - local: .gitlab/common.yml

# The only difference between this file and the build_core_image.yml is that
# it does not have a rules section
build-core:
  extends: .docker_build_script
  stage: build
  variables:
    IMAGE_TAG: "datafed/core"
    GIT_STRATEGY: clone
    DOCKER_FILE_PATH: "core/docker/Dockerfile"
  tags:
    - ci-datafed-core
    - docker
