version: '3.9'


services:

  datafed-repo:
    environment:
      DATAFED_ZEROMQ_SESSION_SECRET: "${DATAFED_ZEROMQ_SESSION_SECRET}"
      DATAFED_ZEROMQ_SYSTEM_SECRET: "${DATAFED_ZEROMQ_SYSTEM_SECRET}"
      DATAFED_DOMAIN: "datafed-core"
      DATAFED_HTTPS_SERVER_PORT: "${DATAFED_HTTPS_SERVER_PORT}"
      DATAFED_DEFAULT_LOG_PATH: "${DATAFED_CONTAINER_LOG_PATH}"
      DATAFED_CORE_ADDRESS_PORT_INTERNAL: "datafed-core:7513"
      DATAFED_GCS_COLLECTION_ROOT_PATH: "/mnt/datafed"
      UID: "${DATAFED_UID}"
      HOST_HOSTNAME: "localhost"
    network_mode: host
    image: datafed-repo:latest
    volumes:
      - ./keys:/opt/datafed/keys
    ports:
      - 9000:9000 # Communication core server

  # Needs host port 80
  datafed-gcs:
    environment:
      DATAFED_ZEROMQ_SESSION_SECRET: "${DATAFED_ZEROMQ_SESSION_SECRET}"
      DATAFED_ZEROMQ_SYSTEM_SECRET: "${DATAFED_ZEROMQ_SYSTEM_SECRET}"
      DATAFED_DOMAIN: "datafed-core"
      DATAFED_HTTPS_SERVER_PORT: "${DATAFED_HTTPS_SERVER_PORT}"
      DATAFED_DEFAULT_LOG_PATH: "${DATAFED_CONTAINER_LOG_PATH}"
      DATAFED_CORE_ADDRESS_PORT_INTERNAL: "datafed-core:7513"
      UID: "${DATAFED_UID}"
      HOST_HOSTNAME: "localhost"
      DATAFED_AUTHZ_USER: "datafed"
      DATAFED_GCS_COLLECTION_ROOT_PATH: "/mnt/datafed"
    network_mode: host
    image: datafed-gcs:latest
    volumes:
      - ./keys:/opt/datafed/keys
      - ./globus:/opt/datafed/globus
      - "${DATAFED_HOST_COLLECTION_MOUNT}:${DATAFED_GCS_COLLECTION_ROOT_PATH}"

# External true indicates that the network is created by a
# separate compose instance
networks:
  datafed-core-secure-api:
    external: true
