version: '3.9'


services:
  datafed-web:
    environment:
      DATAFED_GLOBUS_APP_SECRET: "${DATAFED_GLOBUS_APP_SECRET}"
      DATAFED_GLOBUS_APP_ID: "${DATAFED_GLOBUS_APP_ID}"
      DATAFED_ZEROMQ_SESSION_SECRET: "${DATAFED_ZEROMQ_SESSION_SECRET}"
      DATAFED_ZEROMQ_SYSTEM_SECRET: "${DATAFED_ZEROMQ_SYSTEM_SECRET}"
      DATAFED_DOMAIN: "${DATAFED_DOMAIN}"
      DATAFED_WEB_CERT_PATH: "${DATAFED_WEB_CERT_PATH}"
      DATAFED_WEB_KEY_PATH: "${DATAFED_WEB_KEY_PATH}"
      DATAFED_DEFAULT_LOG_PATH: "${DATAFED_CONTAINER_LOG_PATH}"
      UID: "${DATAFED_UID}"
    image: datafed-web:latest
    ports:
      - 8080:443 

  datafed-core:
    image: datafed-core:latest
    depends_on: ["arango"]
    environment:
      DATAFED_GLOBUS_APP_SECRET: "${DATAFED_GLOBUS_APP_SECRET}"
      DATAFED_GLOBUS_APP_ID: "${DATAFED_GLOBUS_APP_ID}"
      DATAFED_ZEROMQ_SESSION_SECRET: "${DATAFED_ZEROMQ_SESSION_SECRET}"
      DATAFED_ZEROMQ_SYSTEM_SECRET: "${DATAFED_ZEROMQ_SYSTEM_SECRET}"
      DATAFED_DOMAIN: "${DATAFED_DOMAIN}"
      DATAFED_WEB_CERT_PATH: "${DATAFED_WEB_CERT_PATH}"
      DATAFED_WEB_KEY_PATH: "${DATAFED_WEB_KEY_PATH}"
      DATAFED_DEFAULT_LOG_PATH: "${DATAFED_CONTAINER_LOG_PATH}"
      UID: "${DATAFED_UID}"
      DATAFED_DATABASE_PASSWORD: "${DATAFED_DATABASE_PASSWORD}"
      DATAFED_DATABASE_IP_ADDRESS: "${DATAFED_DATABASE_IP_ADDRESS}"
    ports:
      - 7513 # Communication web server
      - 7512 # Secure core server communication

  arango:
    image: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: "${ARANGO_ROOT_PASSWORD}"
    ports:
      - 8529:8529 # Arangodb web UI
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8529/_admin/cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5

