version: '3.9'


services:
  environment:
      DATAFED_GLOBUS_APP_SECRET: "${DATAFED_GLOBUS_APP_SECRET}"
      DATAFED_GLOBUS_APP_ID: "${DATAFED_GLOBUS_APP_ID}"
      DATAFED_ZEROMQ_SESSION_SECRET: "${DATAFED_ZEROMQ_SESSION_SECRET}"
      DATAFED_ZEROMQ_SYSTEM_SECRET: "${DATAFED_ZEROMQ_SYSTEM_SECRET}"
      DATAFED_DOMAIN: "${DATAFED_DOMAIN}"
      DATAFED_WEB_CERT_PATH: "${DATAFED_WEB_CERT_PATH}"
      DATAFED_WEB_KEY_PATH: "${DATAFED_WEB_KEY_PATH}"
      DATAFED_DEFAULT_LOG_PATH: "${DATAFED_DEFAULT_LOG_PATH}"
  datafed-web:
    image: datafed-web:latest
    ports:
      - 8080:443 

  datafed-core:
    image: datafed-core:latest
    environment:
      DATAFED_GLOBUS_APP_SECRET: "${DATAFED_GLOBUS_APP_SECRET}"
      DATAFED_GLOBUS_APP_ID: "${DATAFED_GLOBUS_APP_ID}"
      DATAFED_ZEROMQ_SESSION_SECRET: "${DATAFED_ZEROMQ_SESSION_SECRET}"
      DATAFED_ZEROMQ_SYSTEM_SECRET: "${DATAFED_ZEROMQ_SYSTEM_SECRET}"
      DATAFED_DOMAIN: "${DATAFED_DOMAIN}"
      DATAFED_DATABASE_PASSWORD: "${DATAFED_DATABASE_PASSWORD}"
      DATAFED_DATABASE_IP_ADDRESS: "${DATAFED_DATABASE_IP_ADDRESS}"
      DATAFED_DEFAULT_LOG_PATH: "${DATAFED_DEFAULT_LOG_PATH}"
    ports:
      - 7513 # Communication web server
      - 7512 # Secure core server communication

  arango:
    image: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: "${ARANGO_ROOT_PASSWORD}"
    ports:
      - 8529:8529 # Arangodb web UI
