version: '3.9'


services:

  datafed-web:
    depends_on: ["datafed-core"]
    environment:
      DATAFED_GLOBUS_APP_SECRET: "${DATAFED_GLOBUS_APP_SECRET}"
      DATAFED_GLOBUS_APP_ID: "${DATAFED_GLOBUS_APP_ID}"
      DATAFED_ZEROMQ_SESSION_SECRET: "${DATAFED_ZEROMQ_SESSION_SECRET}"
      DATAFED_ZEROMQ_SYSTEM_SECRET: "${DATAFED_ZEROMQ_SYSTEM_SECRET}"
      DATAFED_DOMAIN: "${DATAFED_DOMAIN}"
      DATAFED_HTTPS_SERVER_PORT: "${DATAFED_HTTPS_SERVER_PORT}"
      DATAFED_WEB_CERT_PATH: "${DATAFED_WEB_CERT_PATH}"
      DATAFED_WEB_KEY_PATH: "${DATAFED_WEB_KEY_PATH}"
      DATAFED_DEFAULT_LOG_PATH: "${DATAFED_CONTAINER_LOG_PATH}"
      DATAFED_CORE_ADDRESS_PORT_INTERNAL: "datafed-core:7513"
      UID: "${DATAFED_UID}"
    image: datafed-web:latest
    volumes:
      - ./keys:/opt/datafed/keys
    networks:
      datafed-internal:
        ipv4_address: 172.16.0.10

  datafed-core:
    image: datafed-core:latest
    depends_on:
      datafed-foxx:
        condition: service_healthy
    environment:
      DATAFED_GLOBUS_APP_SECRET: "${DATAFED_GLOBUS_APP_SECRET}"
      DATAFED_GLOBUS_APP_ID: "${DATAFED_GLOBUS_APP_ID}"
      DATAFED_ZEROMQ_SESSION_SECRET: "${DATAFED_ZEROMQ_SESSION_SECRET}"
      DATAFED_ZEROMQ_SYSTEM_SECRET: "${DATAFED_ZEROMQ_SYSTEM_SECRET}"
      DATAFED_DOMAIN: "${DATAFED_DOMAIN}"
      DATAFED_WEB_CERT_PATH: "${DATAFED_WEB_CERT_PATH}"
      DATAFED_WEB_KEY_PATH: "${DATAFED_WEB_KEY_PATH}"
      DATAFED_DEFAULT_LOG_PATH: "${DATAFED_CONTAINER_LOG_PATH}"
      UID: "${DATAFED_UID}"
      DATAFED_DATABASE_PASSWORD: "${DATAFED_DATABASE_PASSWORD}"
      DATAFED_DATABASE_IP_ADDRESS: "${DATAFED_DATABASE_IP_ADDRESS}"
      DATAFED_DATABASE_IP_ADDRESS_PORT: "${DATAFED_DATABASE_IP_ADDRESS}:${DATAFED_DATABASE_PORT}"
    ports:
      - 7513 # Communication web server
      - 7512 # Secure core server communication
    volumes:
      - ./keys:/opt/datafed/keys
    networks:
      - datafed-core-secure-api
      - datafed-internal

  datafed-foxx:
    image: datafed-foxx:latest
    depends_on: ["arango"]
    environment:
      DATAFED_ZEROMQ_SYSTEM_SECRET: "${DATAFED_ZEROMQ_SYSTEM_SECRET}"
      DATAFED_DOMAIN: "${DATAFED_DOMAIN}"
      DATAFED_DEFAULT_LOG_PATH: "${DATAFED_CONTAINER_LOG_PATH}"
      UID: "${DATAFED_UID}"
      DATAFED_DATABASE_PASSWORD: "${DATAFED_DATABASE_PASSWORD}"
      DATAFED_DATABASE_IP_ADDRESS: "${DATAFED_DATABASE_IP_ADDRESS}"
      DATAFED_DATABASE_HOST: "arango"
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "[ -f /tmp/.foxx_is_installed ]"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - datafed-internal

  arango:
    image: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: "${DATAFED_DATABASE_PASSWORD}"
    ports:
      - 8529:8529 # Arangodb web UI
    networks:
      - datafed-internal

  nginx:
    image: nginx:latest
    depends_on: ["datafed-web"]
    volumes:
      - ./keys:/keys
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 443:443 # this replaces the port that was open on the datafed-web service
    networks:
      - datafed-internal

volumes:
  keys:

networks:
  datafed-core-secure-api:
    driver: bridge
  datafed-internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
  
