version: '3.9'


services:
  datafed-web:
    image: datafed-web:latest
    ports:
      - 8080:443 

  datafed-core:
    image: datafed-core:latest
    environment:
      DATAFED_DOMAIN: "${DATAFED_DOMAIN}"
    ports:
      - 7513 # Communication web server
      - 7512 # Secure core server communication

  arango:
    image: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: "${ARANGO_ROOT_PASSWORD}"
    ports:
      - 8529:8529 # Arangodb web UI
