stages:
  - build

include:
  - local: gitlab_templates/common.yml

build-core:
  extends: .docker_build_script
  stage: build
  variables:
    IMAGE_TAG: "datafed/core"
    GIT_STRATEGY: clone
  tags:
    - ci-datafed-core
    - docker
  rules:
    - changes:
        - docker/**/*
        - scripts/**/*
        - core/**/*
        - common/**/*
        - CMakeLists.txt
        - cmake/**/*
        - .gitlab-ci.yml
      when: on_success

placeholder:
  extends: .placeholder

