stages:
  - build

build-core:
  stage: build
  variables:
    IMAGE_TAG: "datafed/core"
    GIT_STRATEGY: clone
  tags:
    - ci-datafed-core
    - docker
  rules:
    - changes:
        - docker/**/*
        - scripts/**/*
        - core/**/*
        - common/**/*
        - CMakeLists.txt
        - cmake/**/*
        - .gitlab-ci.yml
      when: on_success
  script:
    - BRANCH_LOWER=$(echo "$CI_COMMIT_REF_NAME" | tr '[:upper:]' '[:lower:]')
    - echo "$BRANCH_LOWER"
    - ./scripts/generate_datafed.sh
    - docker login "${REGISTRY}" -u "${HARBOR_USER}" -p "${HARBOR_DATAFED_GITLAB_CI_REGISTRY}"
    - docker build --build-arg DEPENDENCIES="${REGISTRY}/datafed/dependencies-${BRANCH_LOWER}:latest" --build-arg RUNTIME="${REGISTRY}/datafed/runtime-${BRANCH_LOWER}:latest" -f core/docker/Dockerfile -t "${REGISTRY}/${IMAGE_TAG}-${BRANCH_LOWER}:latest" .
    - docker push "${REGISTRY}/${IMAGE_TAG}-${BRANCH_LOWER}"

# Prevents downstream pipeline from being empty and triggering a failure
placeholder:
  stage: build
  tags:
    - docker
  script:
    - echo "placeholder"
 
