name: Jupyter Notebook Linter
on:
  push:
    paths:
      - '**/*.ipynb'
      - '.github/workflows/jupyternotebook-lint.yml'

jobs:
  lint-jupyter:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install nbQA, flake8, and black
        run: |
          pip install nbqa flake8 black

      # Step 4: Run flake8 and black on notebooks in ./jupyter_notebooks folder
      # F821 - Ignore undefined variable errors, these are false positives in jupyter
      #        notebooks if they are defined in a previous cell.
      # F841 - assigned to but unused, appears because the examples have code
      #        that the user will need to fill in.
      # F401 - imported but unused, occurs because the user will need to fill in
      #        parts that require the import.
      - name: Lint Jupyter Notebooks with flake8
        run: nbqa flake8 --ignore=F821,F401,F841 .
        working-directory: jupyter_notebooks

      - name: Format Jupyter Notebooks with black
        run: nbqa black . --check --line-length 80
        working-directory: jupyter_notebooks

      # Step 5: Report status
      - name: Complete
        run: echo "Jupyter Notebook linting completed!"

