name: Unit-Testing
on: push
jobs:
  unit-test:
    runs-on: ubuntu-24.04
    container: debian:bookworm
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - name: Update ubuntu
        run: apt update
      - name: Install Python
        run: . ./scripts/dependency_install_functions.sh && install_python
      - name: Ensure pip is installed
        run: python3.9 -m ensurepip
      - name: Install dependencies
        run: |
          ./scripts/generate_datafed.sh
          ./scripts/install_core_dependencies.sh
      - name: Build
        run: |
          /opt/datafed/dependencies/bin/cmake -S. -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_WEB_SERVER=OFF
          /opt/datafed/dependencies/bin/cmake --build build -j4
      - name: Run tests
        run: |
          /opt/datafed/dependencies/bin/cmake --build build --target test
